# Generated by Django 2.0.2 on 2018-02-17 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbError', models.CharField(max_length=500)),
                ('dbErrorTime', models.DateTimeField(default=datetime.datetime(2018, 2, 17, 16, 47, 9, 904052, tzinfo=utc))),
                ('dbErrorCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPacket', models.CharField(max_length=500)),
                ('dbTime', models.DateTimeField(default=datetime.datetime(2018, 2, 17, 16, 47, 9, 903552, tzinfo=utc))),
            ],
        ),
    ]
