# Generated by Django 2.0.2 on 2018-02-18 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180217_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='dbErrorTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 5, 51, 10, 954098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ping',
            name='dbTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 5, 51, 10, 953056, tzinfo=utc)),
        ),
    ]
