# Generated by Django 2.0.2 on 2018-02-18 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180218_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='dbErrorTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 5, 56, 54, 73163, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ping',
            name='dbTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 5, 56, 54, 72662, tzinfo=utc)),
        ),
    ]
