# Generated by Django 2.0.2 on 2018-02-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180218_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='dbErrorTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ping',
            name='dbTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
