# Generated by Django 2.0.2 on 2018-02-18 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserDataMonit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbLogTime', models.DateTimeField()),
                ('dbTempLimit', models.IntegerField(default=0)),
                ('dbHumidLimit', models.IntegerField(default=0)),
                ('dbHeartbLimit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='logerrormonit',
            name='dbErrorTimeMonit',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 5, 56, 54, 74667, tzinfo=utc)),
        ),
    ]
