# Generated by Django 2.0.2 on 2018-02-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit', '0003_auto_20180219_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loguserdatamonit',
            old_name='dbHeartbLimit',
            new_name='dbHeartbLimitMax',
        ),
        migrations.AddField(
            model_name='loguserdatamonit',
            name='dbHeartbLimitMin',
            field=models.IntegerField(default=0),
        ),
    ]
